ktor:
    application:
        modules:
            - com.gamblippon.ApplicationKt.module
    deployment:
        port: 8080
database:
    jdbcURL: "$JDBC_URL:jdbc:postgresql://localhost:5432/gamblippon"
    driverClassName: "org.postgresql.Driver"
    user: "$DB_USER:root"
    password: "$DB_PASSWORD:TO_DEFINE"
