ktor:
    application:
        modules:
            - com.gamblippon.ApplicationKt.module
    deployment:
        port: 8080
database:
    jdbcURL: "$JDBC_URL:jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
    driverClassName: "org.h2.Driver"
